### ISSUE TITLE
Bundle size should be reduced from 3 MB 

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#102]
## Issue Name
Bundle size should be reduced from 3 MB 

### Summary
Bundle size should be reduced from 3 MB gzipped. 
All rxjs operators are included even those unused in code.
Same for font-awesome icons

### Steps to Reproduce
ng build --prod

### Current Behaviour
Bundle is > 3 MB

### Expected Behaviour
Bundle size should be minimized to < 2MB

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by garethcmurphy** [comment]
![screen shot 2018-10-08 at 09 26 12](https://user-images.githubusercontent.com/16783958/46624834-2dae4880-cb32-11e8-83c1-19c86fb19723.png)

**Comment by lukegorman** [comment]
Is this fixed? current size seems to be 0.8MB

**Comment by garethcmurphy** [comment]
Yes we can make another issue if we want to reduce further
