### ISSUE TITLE
Make it possible to add columns for scientific metadata

### ISSUE THREAD

**Issue by hannes-petri-maxiv-lu-se** [SciCatProject/catanie#126]
### Summary

The user should be able to select entries from the scientific metadata as columns in the dataset table view. In the case of absent values, the corresponding cell will be empty.

### Extra Details

Dependent on #125 which is now complete.

**Comment by toqduj** [comment]
I could do this externally, but a search functionality for scientific metadata field key-value pairs would be nice... Bonus points if this search field can include a range, so I can search for measurements where the transmission factor is outside of the normal range (i.e. T<10% or T>100%) for a sample.
