### ISSUE TITLE
Add link from dataset to proposal and back

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#133]
## Issue Name
Add link from dataset to proposal

### Summary
We need to link from proposal table to relevant dataset
and from dataset detail page to relevant proposal 

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by stephan271** [comment]
The proposalId entry in the dataset table should be replaced by a URL like https://discovery.psi.ch/proposals/20.500.11935%2F20161553 , i.e the URL encoded proposalId inside the URL
