### ISSUE TITLE
Allow multiple selections of facets and individual deletes

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#14]
## Issue Name

MultiFacetSelectUI

### Summary

Currently it is not clear how to select more than one value from a facet and how to get rid of individual selections again. The idea is to either have a button like approach, where the buttons can be deselected,  or a checklist marker next to the dropdown lists

Also one should prevent the possibility to select the same entry more than once.

**Comment by lukegorman** [comment]
I think this functionality is implemented.
