### ISSUE TITLE
Redirect to previous URL after login

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#147]
## Issue Name
Redirect to previous URL after login

### Summary
Logged out users who reach scicat using a deep URL should be redirected to that URL after login, instead of ending up at dashboard

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by lukegorman** [comment]
should this be in the next prod release

**Comment by garethcmurphy** [comment]
if possible
