### ISSUE TITLE
Prevent Edit Popups for non-managers

### ISSUE THREAD

**Issue by stephan271** [SciCatProject/catanie#148]
## Issue Name
PreventPopups

### Summary
The current GUI implementation allows a Edit Popup also for non-managers. This leads later to an access violation, which is not displayed to the user. 

### Steps to Reproduce
As a non-manager try to edit the policy settings. 

### Current Behaviour
A popup appears

### Expected Behaviour
No Popup should be allowed. It will anyway lead to an error when saving. Showing the rows which can not be modified as greyed out text could be helpful.

**Comment by lukegorman** [comment]
done
