### ISSUE TITLE
Improve table interface with more graphics

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#165]
## Issue Name
Improve table interface with more graphics

### Summary

Improve table interface with more graphics, bar for size of file, images

Replace PID with dataset name. (conditional of existence )

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by lukegorman** [comment]
is this about showing thumbnails?

**Comment by garethcmurphy** [comment]
yes and file size graphically

**Comment by garethcmurphy** [comment]
new gui now has images, bar for filesize, icons for table headings
