### ISSUE TITLE
automated performance test

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#166]
## Issue Name

automated performance test

### Summary
automated performance test
running at least once a week
browsing and ingesting 
how long to ingest significant amount of data
how long to browse

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by lukegorman** [comment]
Run tests regularly on separate VM with freshly installed databases in order to create a baseline management which can be repeated any time

**Comment by garethcmurphy** [comment]
create 10 million datasets

**Comment by garethcmurphy** [comment]
added repo to create automatically dataset, to run weekly in jenkins  
https://github.com/SciCatProject/perftest

**Comment by stephan271** [comment]
Added locust based performance framework
