### ISSUE TITLE
Disable check box on dataset overview table for failed archives

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#20]
## Issue Name
re-archive control

### Summary
Currently if an archive fails the dataset table is updated with an entry. The user is able to select this entry check box and issue a repeat archive attempt. This repeat attempt is a problem if there exists some partial dataset on the archive. 

### Steps to Reproduce
Trigger an archive and make it fail somehow.

### Current Behaviour
check box is enabled for failed archive entries
### Expected Behaviour
check box should be disabled
### Extra Details

This issue was highlighted by the archive team at PSI.

**Comment by lukegorman** [comment]
fixed
