### ISSUE TITLE
Resizeable & configurable columns 

### ISSUE THREAD

**Issue by lukegorman** [SciCatProject/catanie#201]
## Issue Name
User feedback: datases table
### Summary

Users are requesting resizeable columns, configurable columns

**Comment by garethcmurphy** [comment]
https://mattlewis92.github.io/angular-resizable-element/#documentation

**Comment by garethcmurphy** [comment]
columns are now configurable but this feature is not rolled out to PSI production yet

**Comment by lukegorman** [comment]
resizeable columns, not required.

Selecteable columns done
