### ISSUE TITLE
Selected datasets list view checkbox

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#21]
## Issue Name
selected dataset checkbox

### Summary
Currently selecting datasets entries in the table adds the dataset to a list on the left. If the user move to another view, the list remains, but there is no clear way to remove the dataset from the list. The proposal is to add a checkbox control to enable disable elements of this list.

### Steps to Reproduce
select entries in the dataset table and move to another view
### Extra Details

Issue raised by archive team

**Comment by lukegorman** [comment]
We think this functionality is made obsolete by the shopping cart functionality.
