### ISSUE TITLE
Login Issue on develop. All users failing to proceed past login screen when using MSAD

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#22]
## Issue Name
Login Issue

### Summary
Possibly only seen at PSI because of the requirement of an active directory authentication process.

### Steps to Reproduce
login using active directory authentication process.

### Current Behaviour
Login is technically successful with a token being generated but the datasets screen is not displayed and the browser remains on the login screen.

in the console:
"ERROR TypeError: err.json is not a function
    at CatchSubscriber.eval [as selector] (user.effects.ts:41)"

Removing the call to json() then shows the actual error:
"TypeError: _this.userSrv.getCurrent(...).switchMap is not a function"

### Expected Behaviour
Dataset table is displayed.

### Extra Details
Adding "import 'rxjs/add/operator/switchMap';"
to catanie/src/app/state-management/reducers/user.reducer.ts
removes the issue.

I'm unsure as to why this fixes the issue and I don't see it as a sufficient fix.

**Comment by lukegorman** [comment]
Is now resolved?

**Comment by lukegorman** [comment]
fix change unknown.
