### ISSUE TITLE
Job Submission after Job submission failure not working

### ISSUE THREAD

**Issue by stephan271** [SciCatProject/catanie#220]
## Issue Name
JobSubmissionAfterFailure

### Summary
After a job was submitted and returned immediately with an error message (e.g. attempting to archive a dataset already archived) then subsequent Job requests seem to be ignored 

### Steps to Reproduce
Run Job twice without reloading GUI in between

### Current Behaviour
Subsequent Jobs, which are okay, are ignored (however this behaviour seems to be not fully reproducable)

### Expected Behaviour
Jobs can always be submitted

**Comment by lukegorman** [comment]
How to force a job to fail for testing purposes?

**Comment by stephan271** [comment]
E.g. archive same dataset twice

-------- Ursprüngliche Nachricht --------
Von: Luke Gorman <notifications@github.com>
Datum: 18.03.2019 14:39 (GMT+01:00)
An: SciCatProject/catanie <catanie@noreply.github.com>
Cc: "Egli Stephan (PSI)" <stephan.egli@psi.ch>, Author <author@noreply.github.com>
Betreff: Re: [SciCatProject/catanie] Job Submission after Job submission failure not working (#220)


How to force a job to fail for testing purposes?
