### ISSUE TITLE
Add physical units to scientific metadata

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#228]
## Issue Name
Add physical units to scientific metadata

### Summary
Currently scientificMetadata has no units.
For metadata from e.g. nexus format, units should be copied and displayed for each figure

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by stephan271** [comment]
The scientific metadata should follow the following convention , i.e. separate value and units into "v" and "u" fields respectively

  "Ring current": {
                "v": 0.402246,
                "u": "A"
            },

**Comment by garethcmurphy** [comment]
added in PR #314
