### ISSUE TITLE
Add search feature within filenames of a dataset

### ISSUE THREAD

**Issue by stephan271** [SciCatProject/catanie#250]
## Issue Name
AddFilenameSearch

### Summary
A search box within the datset detail view on the files tab should allow to filter the displayed filenames according to some search string

### Current Behaviour
No input box to define filter condition/search expression

### Expected Behaviour
Input box for filter exists

**Comment by lukegorman** [comment]
nice, good idea

**Comment by stephan271** [comment]
In fact it would probably better to have an dedicated search filed for filenames within the dataset view, e.g. near to the fulltext search field. Needs index support on catamel side.

**Comment by zjttoefs** [comment]
That sounds related to what you presented today. Isn't it, @stephan271?

**Comment by stephan271** [comment]
Yes, the upcoming catanie version (see branch https://github.com/SciCatProject/catanie/tree/feature/testSharedTableForJobs) will support the search by filename, however rather in its standalone dashboard

**Comment by stephan271** [comment]
Now implemented via files view as shared-table component
