### ISSUE TITLE
live feed

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#276]
## Issue Name

live feed, auto loading, fading color as function of time ? color blindness take into account date chunk view (today/this week). Needs detailed mockup

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by lukegorman** [comment]
potential approach


https://blog.eyas.sh/2018/12/data-and-page-content-refresh-patterns-in-angular/

**Comment by garethcmurphy** [comment]
another approach use loopback Dataset/change-stream and new EventSource in angular.
