### ISSUE TITLE
virtual scrolling assess status for material table

### ISSUE THREAD

**Issue by lukegorman** [SciCatProject/catanie#293]
## Issue Name
virtual scrolling 
### Summary
virtual scrolling assess status for material table

maybe implement.

https://github.com/angular/material2/issues/10122

https://github.com/angular/material2/issues/10122

or wait until material table has support.

**Comment by lukegorman** [comment]
this is not dataset live view!

**Comment by stephan271** [comment]
No virtual scrolling, but avoid of reading unnecessary large data is implemented in shared-table now.
