### ISSUE TITLE
Share data with other users

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#296]
## Issue Name
Share data with other users

### Summary
User should be able to grant access to a dataset to another user

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by garethcmurphy** [comment]
add the other user to a group, which you add to the accessGroups list. Then catanie would need to make a call to update the dataset by adding this group to the dataset's accessGroups and another can to create the group and its members. When the other user re-login he would see the dataset. One would need to discuss were the groups can be managed. This could be either in an IM System like AD or we would create a new group model inside loopback, which would manage these kind of ad hoc groups (i.e re-vive the accessGroups model or somethng similar). I guess this needs some more discussions.

**Comment by lukegorman** [comment]
GUI: 
in the shopping cart, add option for user to share with another user.

BE logic:
user needs a to post a group to catamel with name like AdHocGroup1
then post the members e.g. me
then adds that group to access groups of the relevant DS

**Comment by garethcmurphy** [comment]
Add a share button to dataset details/ shopping cart that allows data to be shared with another user, via form
