### ISSUE TITLE
GUI does not set policy parameters

### ISSUE THREAD

**Issue by stephan271** [SciCatProject/catanie#407]
## Issue Name
PolicyParametersNotSet

### Summary
The backend reports: {"error":{"statusCode":400,"name":"Error","message":"ownerGroupList is a required argument"}}

### Current Behaviour
Policy parameters are not modified when edited

### Expected Behaviour
Policy Parameters are modified when edited

**Comment by lukegorman** [comment]
this was a non issue and was resolved with Klaus. 
access groups was omitted for http request
