### ISSUE TITLE
Attach file(s) to a proposal

### ISSUE THREAD

**Issue by toqduj** [SciCatProject/catanie#413]
We (cc. @ibressler) use standardized (excel) sheets for users to fill in the details of their projects. We use this to fill in the metadata for SciCat, but there is information in the sheet which is not captured in the database. 

We would like to attach the original excel sheet to each proposal, so that if we need to get the additional information, it is but a click away... This may require updating of caramel's Proposal class to include a file link..

Other proposal systems may require the attachment of multiple data files, so support for multiple attachments might be useful..

**Comment by garethcmurphy** [comment]
The attachment model is being overhauled to support proposals and samples as well as datasets.

https://github.com/SciCatProject/catanie/pull/454

**Comment by toqduj** [comment]
Perfect, looking forward to that!

**Comment by zjttoefs** [comment]
Might be fixed now. We'll check and close, if that is the case. @stephan271

**Comment by stephan271** [comment]
https://github.com/SciCatProject/catamel/blob/develop/common/models/proposal.json show that attachments can be linked now to Proposals as well

**Comment by toqduj** [comment]
Super, thanks!
