### ISSUE TITLE
proposal table sort issues

### ISSUE THREAD

**Issue by toqduj** [SciCatProject/catanie#474]
Hi all,

The proposal list in table format looks much better than before. It's having some issues, though:
1. I can't search for proposals based on its metadata (yet)
2. I can't sort by proposalId
3. Sorting by Title or Author does some sort of sort, but certainly not the alphabetical sort I was expecting...

**Comment by henrikjohansson712** [comment]
All of the points mentioned in this issue should now be available.

**Comment by toqduj** [comment]
Thank you very much!
