### ISSUE TITLE
search samples

### ISSUE THREAD

**Issue by toqduj** [SciCatProject/catanie#475]
Searching for samples based on its metadata or sample characteristics would be nice.

**Comment by henrikjohansson712** [comment]
With these features it's now possible to filter samples on sample characteristics in the same way as you can filter datasets on scientific metadata. It does, however, require that the samples characteristics are stored in the following format:
```json
{
    "sampleCharacteristics": {
        "mass": {
            "type": "measurement",
            "value": 5,
            "unit": "grams",
            "valueSI": 0.005,
            "unitSI": "kg"
        },
        "volume": {
            "type": "measurement",
             "value": 1,
             "unit": "cm^3",
             "valueSI": 0.0000010000000000000002,
             "unitSI": "m^3"
        }
    }
}
```
The "type" field is necessary for now, but we're working in removing it. The SI value and unit will be calculated and added automatically by the backend upon saving with the following request:

`PATCH /Samples/{id}`
```json
{
    "sampleCharacteristics": {
        "mass": {
            "type": "measurement",
            "value": 5,
            "unit": "grams"
        },
        "volume": {
            "type": "measurement",
             "value": 1,
             "unit": "cm^3"
        }
    }
}
```
