### ISSUE TITLE
updated entry corrupts the display of datasets

### ISSUE THREAD

**Issue by toqduj** [SciCatProject/catanie#496]
I've just updated a dataset entry using the replaceOrCreate API call, however, this appears to have broken the display of entries in the dataset table. Now, anything after this entry is blank. I can still click on the following items, but they are not being displayed: 

![whoops](https://user-images.githubusercontent.com/5449929/65593227-54a69a00-df90-11e9-9fd6-07ac702997b0.PNG)
 
I first retrieved the PID matching the datasetName. Then I sent the following JSON to the server(sorry it's an image because the Anaconda Powershell Prompt doesn't let me bloody copy and paste..):

![StupidWindowsDoesNotLetMeCopyPaste](https://user-images.githubusercontent.com/5449929/65593430-bb2bb800-df90-11e9-87d5-3dae5ef171c5.PNG)

The visualisation returns to normal when I deselect the dataStatus column for display. However, clicking on the offending dataset shows an empty entry. Could this have something to do with the updating of the history of the dataset?

**Comment by garethcmurphy** [comment]
Datastatus depends on contents of dataset.datasetlifecycle.archivable and retrievable Boolean vale’s so you may have to add these to the JSON. They are automatically added only in the create but not in replace

**Comment by toqduj** [comment]
This doesn't occur if I use the "patch"-request.

**Comment by garethcmurphy** [comment]
can remove replaceOrCreate

**Comment by toqduj** [comment]
That might be a valid solution.

**Comment by lukegorman** [comment]
i will remove (disable) the endpoint

**Comment by stephan271** [comment]
Fixed in catamel commit/f35a4262ca4525e541a53623942e56133f5f1617
