### ISSUE TITLE
Text search issue, ignores ordering of characters?

### ISSUE THREAD

**Issue by toqduj** [SciCatProject/catanie#497]
I wanted to search for datafile entries where the measurement id (and filename) contains the string 0922-103. Two answers were returned, but the second one does not have metadata with the numbers 0922-103, instead it has the numbers 90222-103 as you can see in the screen shot. A minor issue, but still funny. This issue disappears if I put 0922-103 in double quotes in the text search field, like: "0922-103". 

![huh](https://user-images.githubusercontent.com/5449929/65620891-f646df00-dfc2-11e9-85af-b61dd95abc48.PNG)

**Comment by garethcmurphy** [comment]
In this case MongoDb is treating hyphen as a delimiter and searching for 103 and 922

https://docs.mongodb.com/manual/reference/operator/query/text/

**Comment by toqduj** [comment]
Ok, so would it be a solution to cast any input in that text field to a string? Or would that disable any advanced text search functionality ("A" and "B" not "C", or so?)...

**Comment by garethcmurphy** [comment]
We will wrap this in quotes

**Comment by garethcmurphy** [comment]
Note: quotes around individual words as long as the person did not put quotes in

**Comment by garethcmurphy** [comment]
move to catamel

**Comment by stephan271** [comment]
The new File view allows to make arbitrary substring searches on the filename directly
