### ISSUE TITLE
Proposal viewer not updating "main proposer" and "principle investigator" for current proposal

### ISSUE THREAD

**Issue by toqduj** [SciCatProject/catanie#533]
If I go through our list of proposals, and click on one proposal, then go back and click on the next proposal, the values in the fields for "main proposer" and "principal investigator" still contain the people from the previously viewed proposal. 

If I click "view metadata", the correct person is listed in there, so it probably has to do with the loading of the personId in the background?

**Comment by garethcmurphy** [comment]
Hi Brian,

This was a known issue, which should have been corrected in the more recent version of Catanie. I recommending updating catanie and the issue should stop.

Best wishes,

Gareth

Gareth
