### ISSUE TITLE
Proposal stage could be a field

### ISSUE THREAD

**Issue by toqduj** [SciCatProject/catanie#534]
We are having more than 50 proposals at the moment, and it is getting harder to keep track of them. Most of these proposals are from finished projects, some of these are still in the draft stage. Would it be an idea to add the proposal status to the keywords? (e.g. draft/submitted/scheduled/running/post-run/completed/rejected)

**Comment by garethcmurphy** [comment]
Hi Brian, 

Thanks for your input which is always interesting and useful! After discussing proposals at length in our triage meeting, we have the following response.
We are using the user office as the single source of truth for keeping track of proposals and proposal state. SciCat is primarily a data catalogue and duplicating proposal state in both the user office and metadata catalogue risks having outdated information on one or both systems, as well as adding a strong interdependency and blurring the roles of the two systems. For these reasons we have no current plans to add proposal state in both the metadata catalogue, SciCat and the user office software.

Best wishes,

Gareth

**Comment by toqduj** [comment]
Alright, thanks for the clarification and discussion!
