### ISSUE TITLE
Out of date file location

### ISSUE THREAD

**Issue by nvaytet** [SciCatProject/catanie#545]
When searching for file `nicos_00000039.hdf`, I arrived at this page

https://scicat.esss.dk/datasets/20.500.12269%2FBRIGHTNESS%2FV200053

Which states that the file is located at:
`/nfs/groups/beamlines/v20/nicos_00000039.hdf`
when in reality the file sits inside the `67JH32` directory, i.e.
`/nfs/groups/beamlines/v20/67JH32`

I have not checked whether this is the only file or if this is also the case for others.

**Comment by garethcmurphy** [comment]
I will fix that and check for other misplacements

**Comment by stephan271** [comment]
Closed due to inactivity - probably fixed . Reopen if required
