### ISSUE TITLE
Wrong email for submitted jobs

### ISSUE THREAD

**Issue by stephan271** [SciCatProject/catanie#58]
## Issue Name
WrongEmailAddress

### Summary
When submitting archive or retrieve jobs the wrong email address taken from User model is used instead of the one from UserIdentity

### Current Behaviour
Takes dummy email created inside User collection

### Expected Behaviour
Should take the email from UserIdentity for real users

### Extra Details
The logic to extract the email from UserIdentity is inside the getEmail effect, but it seems that this effect is never called

**Comment by garethcmurphy** [comment]
fixed in https://github.com/SciCatProject/catanie/pull/66
