### ISSUE TITLE
properly toggle logbook functionality

### ISSUE THREAD

**Issue by lukegorman** [SciCatProject/catanie#599]
dataset detail throws errors because logbook fields are null.

this shouldnt happen when logbook is toggled off

**Comment by henrikjohansson712** [comment]
Could you describe the errors you're getting? I have tried to reproduce by setting logbook to disabled but couldn't see anything.

**Comment by henrikjohansson712** [comment]
I think I've found what causes the error. I'll create a pr with a possible fix so you can check it out.
