### ISSUE TITLE
Shared filter component

### ISSUE THREAD

**Issue by lukegorman** [SciCatProject/catanie#636]
## Issue Name
Shared filter component

### Summary

something in line with the shared table component. A filter component as seen on the dataset table view.

Along with this we will need a generic back end implementation.

**Comment by lukegorman** [comment]
@henrikjohansson712 do you have some thoughts on this.

**Comment by henrikjohansson712** [comment]
I think it would be a good idea. Could probably be done without making changes to the back end if we handle the component output in the parent component.

**Comment by stephan271** [comment]
Implemented in the shared-table component via column filters.
