### ISSUE TITLE
browser state persisting between login sessions

### ISSUE THREAD

**Issue by lukegorman** [SciCatProject/catanie#655]
### Summary
the browser state is cleared after logout

### Steps to Reproduce
-log in and navigate to any component with some data available. e.g. policies.
-log out
-log in with another user with access to different groups
-navigate to the component

It is possible to see records from the previous users session.

**Comment by henrikjohansson712** [comment]
Fixed in commit d39c8ae90755ebc357b201c1150a6dd0ee3ee915. All states are now cleared on logout.
