### ISSUE TITLE
Create state management for orig datablocks

### ISSUE THREAD

**Issue by lukegorman** [SciCatProject/catanie#668]
### Summary

currently origdata is fetched as part of a relation query with datasets and is stored as part of the dataset store.

This causes a huge demand on the backend.

findFilesByName()  

Do we need to have an independent store for origdatablocks or is i enough just to change to API call.

**Comment by stephan271** [comment]
This issue will be covered by replacing the current file view in dataset details by the shared-table approach

**Comment by stephan271** [comment]
Replaced by #847
