### ISSUE TITLE
How to disable anonymous access?

### ISSUE THREAD

**Issue by tschoonj** [SciCatProject/catanie#692]
Hi,

The current catanie:latest docker image does not seem to have an anonymous mode (accessing data without logging in).

I cannot reproduce this with the latest develop branch though: is there a setting available to disable the anonymous mode?

Thanks,

Tom

**Comment by henrikjohansson712** [comment]
Turns out it has been a year since we last built a latest image of catanie. I have fixed that now and a fresh catanie:latest image should be available on Docker Hub.

No, there's no setting to disable the anonymous mode.

Best regards,
Henrik
