### ISSUE TITLE
Create a CLI for ingesting data to data catalog

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#7]
Should allow to define sourcefolder and meta data by a user, who has access to the data files. 
Especially useful for derived data
Could also be in charge of copying "local" datafiles to central file server for later access via archive system.
A definition of a "standard" sidecar file (JSON format) with a defined schema would be helpful.

Initial discussion with Chris resulted in creating a version based on the Go language.

In a subsequent step a GUI version, whcih would allow to browse through the local filesystem and to select files from there will be added. Technology not yet defined (Electron, kivi, Qt application ...)

**Comment by lukegorman** [comment]
Only the GUI parts remains outstanding. Not sure if we really want it.
