### ISSUE TITLE
Proposal filter is not working

### ISSUE THREAD

**Issue by nguyenlinhlinh** [SciCatProject/catanie#756]
### Summary
User gets no proposal when filtering proposals by date range.
### Steps to Reproduce
Go to proposal page and try to filter proposals with a date range that you known Scicat should return at least one proposal. 
### Current Behaviour
Returns no proposal.
### Expected Behaviour
Returns proposal in that date range.

**Comment by stephan271** [comment]
I think the proposal page is a good candidate to be replaced by the shared-table implementation. Then we do not need to fix this bug... I would recommend go this way. Any volunteers ?

**Comment by nguyenlinhlinh** [comment]
I can volunteer if you think I can manage to do that(Not sure about the requirements on shared-table). I thought you are working on the shared-table you showed us some time ago or it was for something else?

**Comment by stephan271** [comment]
Yes, I was working on it, but now it is in a state where it can be used for other use cases (I hope) . You could e.g. follow the example of the Job display. You should need only few things to replace the current implementation. Let me know if you need help. And thanks for volunteering. BTW: if you find a feature is missing in shared table (and that will be the case...) let us know and then we can try to add it at the same time...

**Comment by nguyenlinhlinh** [comment]
I tried out the shared table and it looks like below. Since the proposal has startTime and endTime I am not sure how the filter function should be. I am thinking that startTime and endTime each has a filter which can compare greaterThan or lessThan or between. Or they both should share a column and have a filter by date range. 
Another thing is the Author column, it is a combination of firstname and surename. Since the id property can only take one string the column Author can only show firstname. 
![Screenshot 2021-04-14 at 10 58 27](https://user-images.githubusercontent.com/17545757/114683763-96349c80-9d10-11eb-82d6-1980254e07d5.png)

**Comment by stephan271** [comment]
I would restructure the columns to follow the structure as defined in the proposal model (proposal.json) directly (may be one skipp some columns with redundant infos, not sure however). For the date fields I would use the between filter.

**Comment by nguyenlinhlinh** [comment]
Sovled by #772
