### ISSUE TITLE
Wrong field casting when editing metadata

### ISSUE THREAD

**Issue by minottic** [SciCatProject/catanie#770]
### Summary
When adding or editing string field and inserting numeric value, on save, field is converted to date, with value 1970/1/1...
This happens during editing of nested scientific metadata and probably is a side effect of #755 
### Steps to Reproduce
![image](https://user-images.githubusercontent.com/50220438/116736712-8c898500-a9f0-11eb-95de-6238b99d3889.png)
![image](https://user-images.githubusercontent.com/50220438/116736767-9ad7a100-a9f0-11eb-9070-c8fa218e249d.png)
![image](https://user-images.githubusercontent.com/50220438/116736800-a6c36300-a9f0-11eb-973e-79c0a1b80291.png)
### Current Behaviour
String field is converted to date, with value 1970/1/1.
### Expected Behaviour
Keep string and cast numeric value to string 
### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by nguyenlinhlinh** [comment]
Hi @minottic, I tried to reproduce the bug but it doesn't show up. Could you please check again to see if you have the latest changes? otherwise maybe you can show it to me on the meeting tomorrow.

**Comment by minottic** [comment]
Hi @nguyenlinhlinh , dunno, maybe it then relates to something else. I will have a better look, and let's touch on it tomorrow during the meeting if I keep seeing the same behavior. Thanks!

**Comment by nguyenlinhlinh** [comment]
@minottic I am suspecting that this [function](https://github.com/SciCatProject/catanie/blob/e751564a773f2c2943591619109dbaea3dd839ad/src/app/shared/modules/scientific-metadata-tree/base-classes/tree-base.ts#L190) is the one causing the bug but I can't not reproduce it. Could you check if the code for this function in your deployment looks the same?

**Comment by nguyenlinhlinh** [comment]
Ah I could reproduce the bug now with value "1000" shall try to fix that
