### ISSUE TITLE
Browser cache problems when deploying new program releases

### ISSUE THREAD

**Issue by stephan271** [SciCatProject/catanie#78]
## Issue Name
BrowserCacheIssue

### Summary
Users sometimes have to explicitly flush their browser cache to get the new correct version of  a program

### Current Behaviour
User continues to use the old version from the cached contents in the browser

### Expected Behaviour
User always gets the newest released version, without the need to clear the browser cache

**Comment by garethcmurphy** [comment]
In index.html:

  <meta http-equiv="cache-control" content="no-cache, must-revalidate, post-check=0, pre-check=0">
  <meta http-equiv="expires" content="0">
  <meta http-equiv="pragma" content="no-cache">
In Nginx conf /etc/nginx/conf.d/default.conf:

server {
  //  ...
  location / {
    try_files $uri $uri/ /index.html =404;
    expires       0;
    add_header    Cache-Control  public;
    add_header    Cache-Control  no-store;
    add_header    Cache-Control  no-cache;
  }
  //  ...
}

**Comment by lukegorman** [comment]
we think this is a non issue. We think it was related to log file space on kubernetes filling up. Resolution is kubernetes management.
