### ISSUE TITLE
Add "expert" Query option for sophisticated queries

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#8]
The idea would be to enable the end user to use the full power of the loopback (or Mongo) Query engine, e.g queries equivalent to Mongo DB native queries like the following:

db.RawDataset.find( {"scientificMetadata.entry.data.spec.attrs.idgap" : {$gt: 4.0, $lt: 5.0}}, {"scientificMetadata.entry.data.spec.attrs.idgap":1, "scientificMetadata.entry.sample.name":1})

Further details need to be discussed before we start any implementation

**Comment by lukegorman** [comment]
fullquery/fullfacet now supports arbitrary complex queries via the "mode" keyword so the majority of work is in the GUI.
